### ISSUE TITLE
Any update for 4.3.1?

### ISSUE THREAD

**Issue by phpbits** [GreenThemes/GT-Theme-Customizer-Preview#4]
Hi,

Just trying out and it seems to be not working on the latest version. Any update plans? Thanks!

**Comment by Larceniii** [comment]
Sure I'll give it a look over. Has it been working good for you? I received so little feedback I wasn't sure it was of use to anyone but me.

**Comment by Larceniii** [comment]
Ok, commiting changes now. New version should work with WP 4.3.1

**Comment by Larceniii** [comment]
You can test it live here http://greenthe.me/ I believe it's working now.

**Comment by phpbits** [comment]
That was fast :) Will check it. Thank you very much!

**Comment by Larceniii** [comment]
No problem, I get email notifications and if people work with me I like
helping them in return. Also I'm pretty efficient. Like right now I'm at a
party drinking lol
